### ISSUE TITLE
No arcade vertical games

### ISSUE THREAD

**Issue by heloisatech** [batocera-linux/batocera-emulationstation#1188]
After last update v34, collection vertical games disappeared.
In v32 and v33 it worked

![20220517_141022](https://user-images.githubusercontent.com/6962212/168884979-c1e2dd33-3706-44c9-b562-0eb548c6aae8.jpg)

**Comment by fabricecaruso** [comment]
The mamenames.xml file was invalid. It's fixed now & will be OK for the next build.

**Comment by heloisatech** [comment]
@fabricecaruso In the last v34 update 5/19 it still doesn't appear
